version: '3.6'

services:
  jenkins:
    container_name: jenkins
    tty: true
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8088:8080"
      - "50000:50000"
    volumes:
      - ../data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock