version: '3.6'

services:
  elasticsearch_5.6.0:
    container_name: elasticsearch_5.6.0
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - node.data=true
      - network.publish_host=127.0.0.1
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "../data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - 9200
      - 9300
  kibana_5.6.0:
    container_name: kibana_5.6.0
    image: docker.elastic.co/kibana/kibana:5.6.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch_5.6.0:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601