version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - node.data=true
      - network.publish_host=127.0.0.1
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "../data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
  kibana:
    container_name: kibana 
    image: docker.elastic.co/kibana/kibana:5.6.0
    ports:
      - 5601:5601