version: '3'
version: '3.6'

services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:5.15.6
    volumes:
      - ../data:/opt/activemq/data
    ports:
      - 1883:1883
      - 5672:5672
      - 8161:8161
      - 61613:61613
      - 61614:61614
      - 61616:61616

# 61616 JMS
# 8161  UI
# 5672  AMQP  (since `rmohr/activemq:5.12.1`)
# 61613 STOMP (since `rmohr/activemq:5.12.1`)
# 1883  MQTT  (since `rmohr/activemq:5.12.1`)
# 61614 WS    (since `rmohr/activemq:5.12.1`)