version: '3.6'
services:
  mariadb10.3:
    container_name: mariadb10.3
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: TEST
      MYSQL_DATABASE: TEST
      MYSQL_USER: TEST
      MYSQL_PASSWORD: TEST
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - ../data:/var/lib/mysql