version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx-container
    ports: ['8080:80']
    networks:
      static-network:
        ipv4_address: 172.20.128.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16