version: '3.6'

services:
  postgres_10:
    container_name: postgres_10
    environment: 
      POSTGRES_DB: TEST
      POSTGRES_PASSWORD: TEST
      POSTGRES_USER: TEST
    image: postgres:10
    ports: 
      - 5432:5432
    volumes: 
      - ../data:/var/lib/postgresql/data
    restart: always
