version: '3.6'

services:
  postgres_11_master:
    container_name: postgres_11_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
    image: bitnami/postgresql:11
    ports: 
      - "5432:5432"
    volumes: 
      - ../data:/bitnami/postgresql
    restart: always
  postgres_11_slave:
    container_name: postgres_11_slave
    image: 'bitnami/postgresql:11'
    ports:
      - "5432"
    depends_on:
      - postgres_11_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgres_11_master
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
