services:
  adminer:
    image: adminer
    ports: ['8081:8080']
    restart: always
  db:
    environment: 
      POSTGRES_DB: TEST
      POSTGRES_PASSWORD: TEST
      POSTGRES_USER: TEST
    image: postgres:10
    ports: 
      - 5432:5432
    volumes: 
      - ../data:/var/lib/postgresql/data
    restart: always
version: '3.1'