services:
  adminer:
    image: adminer
    ports: ['8081:8080']
    restart: always
  db:
    environment: 
      POSTGRES_DB: ${SERVICE_DATABASE}
      POSTGRES_PASSWORD: ${SERVICE_DATABASE_PASSWORD}
      POSTGRES_USER: ${SERVICE_DATABASE_USERNAME}
    image: postgres:10
    ports: 
      - ${SERVICE_DATABASE_PORT}:5432
    volumes: 
      - ../data:/var/lib/postgresql/data
    restart: always
version: '3.1'